name: Mirror internal to GitHub

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror from internal repo
        run: |
          git clone --mirror ssh://git@g.strm.sh/nix/hermes.git hermes-mirror.git
          cd hermes-mirror.git
          git push --mirror "$GITHUB_MIRROR_URL"
        env:
          GITHUB_MIRROR_URL: https://github.com/rafa-dot-el/nix-hermes.git
          GIT_SSH_COMMAND: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=accept-new
